---
inherit_from: '.rubocop_todo.yml'
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - '.vendor/**/*'

Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/IndentArray:
  EnforcedStyle: 'consistent'
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: 'new_line'
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: 'same_line'
Layout/MultilineHashBraceLayout:
  EnforcedStyle: 'new_line'
Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: 'new_line'

Metrics/BlockLength:
  Description: 'Do not force abitrary block length.'
  Enabled: false
Metrics/MethodLength:
  Description: 'Do not force abitrary method length.'
  Enabled: false
Metrics/ClassLength:
  Description: 'Do not force abitrary class length.'
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Description: 'Complexity is very relative.'
  Enabled: false
Metrics/LineLength:
  Description: 'Wrapping code too much makes it harder to read.'
  Enabled: false
Metrics/PerceivedComplexity:
  Description: '"Complexity" is very relative'
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true
Style/BlockDelimiters:
  EnforcedStyle: 'braces_for_chaining'
Style/BracesAroundHashParameters:
  EnforcedStyle: 'context_dependent'
Style/ClassAndModuleChildren:
  Description: 'Compact style reduces the required amount of indentation.'
  EnforcedStyle: 'compact'
Style/Encoding:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
    - 'puts'
    - 'require'
    - 'include'
    - 'it'
    - 'context'
    - 'describe'
    - 'to'
    - 'to_not'
    - 'raise'
    - 'desc'
    - 'task'
    - 'exit'
    - 'should'
    - 'gem'
    - 'group'
    - 'attr_reader'
    - 'attr_accessor'
    - 'attr_writer'
    - 'source'
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: 'percent_r'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'no_comma'
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/FormatStringToken:
  Enabled: false
Style/FileName:
  Exclude:
    - 'lib/puppet-lint.rb'
    - 'lib/puppet-lint/tasks/puppet-lint.rb'
    - 'spec/puppet-lint_spec.rb'
